# This is a basic workflow to help you get started with Actions

name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=https://talend.github.io/pendo-product-tracking-demo/
          browser: chrome
          headless: true
