name: Weekly cross-browser testing
on: push
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
      - name: Github Action for wget
        # You may pin to the exact commit or the version.
        # uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
        uses: wei/wget@v1.1.1
        with:
          args: -qO- https://talend.github.io/pendo-product-tracking-demo/
