name: CI build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */6 * * *'
jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        python setup.py install
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
        sudo apt-get install firefox
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver and geckodriver (Firefox Webdriver)
      run: |
        seleniumbase install chromedriver
        seleniumbase install geckodriver
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    - name: Run pytest my_first_test.py --browser=firefox --headless
      run: |
        pytest test.py --browser=firefox --headless -v -s --junit-xml=junit/test-results.xml
